
CREATE DATABASE customer_behavior_analysis;

USE customer_behavior_analysis;

SELECT * FROM customer LIMIT 10;

#  What is the total revenue generated by male vs female customers?

SELECT  gender, SUM(purchase_amount) AS total_revenue FROM customer GROUP BY gender;

# Which customers used a discount but still spent more than the avergae purchase amount?

SELECT customer_id, purchase_amount  FROM customer WHERE purchase_amount >=(SELECT AVG(purchase_amount) as Avg_amount FROM customer)
AND discount_applied = 'Yes';

# Which are the Top 5 products with the highest average review rating?

SELECT item_purchased , ROUND(AVG(review_rating),2) as avg_rating FROM customer group by item_purchased ORDER BY AVG(review_rating) DESC LIMIT 5;

# Compare the average Purchase Amounts between Standard and Express Shipping

SELECT shipping_type, ROUND(AVg(purchase_amount),2) AS avg_amount FROM customer GROUP BY shipping_type HAVING shipping_type IN ('Express','Standard');

# Do subscribed customers spend more? Compare Avergae spend and total revenue between subscribers and non-subscribers

SELECT subscription_status,COUNT(*) as total_customers,ROUND(AVG(purchase_amount),2) as avg_spend,
 ROUND(SUM(purchase_amount),2) as total_revenue FROM customer GROUP BY subscription_status;
 
 # Which 5 products have the highest percentage of purchases with discount appplied?
 
 
 SELECT item_purchased,
 ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
 AS discount_rate
 FROM customer GROUP BY item_purchased
 ORDER BY discount_rate DESC
 LIMIT 5;
 
 # Segment customers into New, Returning and loyal based on their total number of previous purchase and show the cpunt of each segment.
 
 WITH customer_types as (
 SELECT customer_id, previous_purchases,
 CASE
 WHEN previous_purchases =1 THEN 'New'
 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
 ELSE 'Loyal'
 END AS 'Customer_Status'
 FROM customer
)

SELECT Customer_Status, count(*) as 'Number of Customers' FROM customer_types GROUP BY Customer_Status;
 
# What are the top 3 most purchased products within each category

WITH item_count as(

SELECT category, item_purchased, COUNT(*) AS total_purchase, ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS product_rank FROM customer 
GROUP BY category, item_purchased)

 SELECT product_rank, category, item_purchased, total_purchase FROM item_count WHERE product_rank <=3;

 
 # Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 
SELECT subscription_status, count(*) as repeat_customers from customer WHERE previous_purchases>5 GROUP BY subscription_status;
 
 
 # What is the revenue contribution of each age group?
 
SELECT age_group, SUM(purchase_amount) as Total_Revenue FROM customer GROUP BY age_group ORDER BY Total_Revenue DESC;
 


